const NODE = "/home/swdc-kjsse/.nvm/versions/node/v22.19.0/bin/node";
const NPM = "/home/swdc-kjsse/.nvm/versions/node/v22.19.0/bin/npm";

module.exports = {
    apps: [
        {
            name: "eventio-backend",
            script: "main.js",
            interpreter: NODE,
            cwd: "/vm-storage/projects/eventio-3.0/backend",
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "512M",
            env: {
                NODE_ENV: "production",
                PORT: "3500",
            },
            out_file: "/tmp/eventio/backend.log",
            error_file: "/tmp/eventio/backend.log",
            merge_logs: true,
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        },
        {
            name: "eventio-app",
            script: NPM,
            args: "run start -- --port 4173",
            interpreter: NODE,
            cwd: "/vm-storage/projects/eventio-3.0/frontend/app",
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "512M",
            env: {
                NODE_ENV: "production",
                PORT: "4173",
            },
            out_file: "/tmp/eventio/app.log",
            error_file: "/tmp/eventio/app.log",
            merge_logs: true,
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        },
        {
            name: "eventio-council-app",
            script: NPM,
            args: "run start -- --port 4174",
            interpreter: NODE,
            cwd: "/vm-storage/projects/eventio-3.0/frontend/council-app",
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "512M",
            env: {
                NODE_ENV: "production",
                PORT: "4174",
            },
            out_file: "/tmp/eventio/council-app.log",
            error_file: "/tmp/eventio/council-app.log",
            merge_logs: true,
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        },
        {
            name: "eventio-faculty",
            script: NPM,
            args: "run start -- --port 4175",
            interpreter: NODE,
            cwd: "/vm-storage/projects/eventio-3.0/frontend/faculty",
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "512M",
            env: {
                NODE_ENV: "production",
                PORT: "4175",
                NEXT_PUBLIC_SERVER_ADDRESS: "https://eventioapi.swdc.somaiya.edu",
            },
            out_file: "/tmp/eventio/faculty.log",
            error_file: "/tmp/eventio/faculty.log",
            merge_logs: true,
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        },
    ],
};
