export const branchOptions: { [key: string]: string[] } = {
  '2025': [
    'Computer Engineering',
    'Information Technology',
    'Electronics',
    'Mechanical',
    'Electronics And Telecommunications',
  ],
  '2026': [
    'Computer Engineering',
    'Information Technology',
    'Mechanical',
    'Electronics And Telecommunications',
    'Electronics And Computers',
  ],
  '2027': [
    'Computer Engineering',
    'Computer And Communication',
    'Information Technology',
    'Artificial Intelligence And Data Science',
    'Mechanical',
    'Electronics And Telecommunications',
    'Electronics And Computers',
    'Robotics And Artificial Intelligence',
  ],
  '2028': [
    'Computer Engineering',
    'Computer And Communication',
    'Computer Science And Business Systems',
    'Information Technology',
    'Artificial Intelligence And Data Science',
    'Mechanical',
    'Electronics And Telecommunications',
    'Electronics And Computers',
    'Electronics VLSI',
    'Robotics And Artificial Intelligence',
  ],'2029': [
    'Computer Engineering',
    'Computer And Communication',
    'Computer Science And Business Systems',
    'Information Technology',
    'Artificial Intelligence And Data Science',
    'Mechanical',
    'Electronics And Telecommunications',
    'Electronics And Computers',
    'Electronics VLSI',
    'Robotics And Artificial Intelligence',
    'Other'
  ],
};
